services:
  - type: web
    name: sentiment-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /mnt/cache
    plan: free
